#!/usr/bin/env bash


sed -i '/base/{n;N;N;d}' $HOME/.config/polybar/config
sed -i "/base/ a\
include-file = ${HOME}/.config/polybar/master.conf" $HOME/.config/polybar/config
sed -i "/base/ a\
include-file = ${HOME}/.config/polybar/modules.conf" $HOME/.config/polybar/config
sed -i "s/liveuser/${USER}/g" $HOME/.mozilla/firefox/archlabs.default/prefs.js
sed -i "s/liveuser/${USER}/g" $HOME/.mozilla/firefox/archlabs.default/sessionstore.js
sed -i "s/liveuser/${USER}/g" $HOME/.gorice/templates/i3/data.json
sed -i "s/liveuser/${USER}/g" $HOME/.config/gtk-3.0/bookmarks

sed -i '/setup/d' $HOME/.config/openbox/autostart
rm -f $HOME/.config/setup
